apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-producer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "api-producer.fullname" . }}
spec:
{{- if not .Values.keda.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: {{ include "api-producer.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "api-producer.fullname" . }}
    spec:
      containers:
        - name: api-producer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.redisSecretName }}
                  key: {{ .Values.env.redisSecretKey }}
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: RABBITMQ_URL
            - name: CORS_ORIGINS
              value: {{ .Values.env.corsOrigins | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.env.otelExporterOtlpEndpoint | quote }}
            - name: OTEL_SERVICE_NAME
              value: "api-producer"
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
{{- end }}
