{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "api-producer.fullname" . }}-scaler
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: {{ include "api-producer.fullname" . }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: {{ .Values.keda.scaleDownStabilizationWindowSeconds }}
  triggers:
    - type: prometheus
      metadata:
        serverAddress: {{ .Values.keda.prometheusServerAddress | quote }}
        query: sum(rate(http_requests_total{job="api-producer",endpoint!="/health",endpoint!="/metrics"}[{{ .Values.keda.rateWindow }}]))
        threshold: {{ .Values.keda.threshold | quote }}
        activationThreshold: {{ .Values.keda.activationThreshold | quote }}
{{- end }}
