{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  RABBITMQ_URL: {{ .Values.secret.rabbitmqUrl | quote }}
{{- end }}
